import api from '../api/axios';

export const employerApi = {
  profile: () => api.get('/employers/profile').then((res) => res.data),
  saveProfile: (payload) => api.patch('/employers/profile', payload).then((res) => res.data),
  dashboard: () => api.get('/employers/dashboard').then((res) => res.data),
  jobs: () => api.get('/employers/jobs').then((res) => res.data),
  team: () => api.get('/employers/team').then((res) => res.data),
  saveTeamMember: (payload) => api.post('/employers/team', payload).then((res) => res.data),
  updateTeamMember: (memberId, payload) => api.patch(`/employers/team/${memberId}`, payload).then((res) => res.data),
  removeTeamMember: (memberId) => api.delete(`/employers/team/${memberId}`).then((res) => res.data),
  savedViews: (params = {}) => api.get('/employers/saved-views', { params }).then((res) => res.data),
  saveView: (payload) => api.post('/employers/saved-views', payload).then((res) => res.data),
  talentPool: (params = {}) => api.get('/employers/talent-pool', { params }).then((res) => res.data),
  createTalent: (payload) => api.post('/employers/talent-pool', payload).then((res) => res.data),
  updateTalent: (talentId, payload) => api.patch(`/employers/talent-pool/${talentId}`, payload).then((res) => res.data),
  offers: () => api.get('/employers/offers').then((res) => res.data),
  createOffer: (payload) => api.post('/employers/offers', payload).then((res) => res.data),
  updateOfferStatus: (offerId, payload) => api.patch(`/employers/offers/${offerId}/status`, payload).then((res) => res.data),
  activityCalendar: () => api.get('/employers/activity-calendar').then((res) => res.data),
  approvals: () => api.get('/employers/approvals').then((res) => res.data),
  createApproval: (payload) => api.post('/employers/approvals', payload).then((res) => res.data),
  updateApproval: (approvalId, payload) => api.patch(`/employers/approvals/${approvalId}`, payload).then((res) => res.data),
  allocations: () => api.get('/employers/allocations').then((res) => res.data),
  saveAllocation: (payload) => api.post('/employers/allocations', payload).then((res) => res.data),
  updateAllocation: (allocationId, payload) => api.patch(`/employers/allocations/${allocationId}`, payload).then((res) => res.data),
  removeAllocation: (allocationId) => api.delete(`/employers/allocations/${allocationId}`).then((res) => res.data),
  policies: () => api.get('/employers/policies').then((res) => res.data),
  savePolicy: (payload) => api.post('/employers/policies', payload).then((res) => res.data),
  updatePolicy: (policyId, payload) => api.patch(`/employers/policies/${policyId}`, payload).then((res) => res.data),
  configurations: () => api.get('/employers/configurations').then((res) => res.data),
  updateConfigurations: (payload) => api.patch('/employers/configurations', payload).then((res) => res.data),
  exportCenter: () => api.get('/employers/exports').then((res) => res.data),
  interviewCalendar: () => api.get('/employers/interviews/calendar').then((res) => res.data),
  interviewHub: () => api.get('/employers/interviews/hub').then((res) => res.data),
  createInterviewRound: (applicationId, payload) => api.post(`/employers/applications/${applicationId}/interview-rounds`, payload).then((res) => res.data),
  updateInterviewRound: (applicationId, roundId, payload) => api.patch(`/employers/applications/${applicationId}/interview-rounds/${roundId}`, payload).then((res) => res.data),
  sendInterviewReminders: () => api.post('/employers/interviews/send-reminders').then((res) => res.data),
  applicants: (jobId, params = {}) => api.get(`/employers/jobs/${jobId}/applications`, { params }).then((res) => res.data),
  bulkApplicants: (payload) => api.patch('/employers/applications/bulk', payload).then((res) => res.data),
  saveInterviewSlots: (applicationId, payload) => api.put(`/employers/applications/${applicationId}/slots`, payload).then((res) => res.data),
  bookInterviewSlot: (applicationId, payload) => api.post(`/employers/applications/${applicationId}/book-slot`, payload).then((res) => res.data),
  updateApplicantStatus: (applicationId, payload) => api.patch(`/employers/applications/${applicationId}/status`, payload).then((res) => res.data)
};
