const router = require('express').Router();
const employerController = require('../controllers/employer.controller');
const { protect } = require('../middlewares/auth.middleware');
const { authorizeRoles } = require('../middlewares/role.middleware');
const { ROLES } = require('../utils/constants');

router.use(protect);
router.use(authorizeRoles(ROLES.EMPLOYER, ROLES.ADMIN));

router.get('/profile', employerController.getProfile);
router.patch('/profile', employerController.upsertProfile);
router.get('/dashboard', employerController.dashboard);
router.get('/jobs', employerController.listMyJobs);
router.get('/team', employerController.getHiringTeam);
router.post('/team', employerController.upsertHiringTeamMember);
router.patch('/team/:memberId', employerController.upsertHiringTeamMember);
router.delete('/team/:memberId', employerController.removeHiringTeamMember);
router.get('/saved-views', employerController.getSavedViews);
router.post('/saved-views', employerController.saveSavedView);
router.get('/talent-pool', employerController.listTalentPool);
router.post('/talent-pool', employerController.createTalentEntry);
router.patch('/talent-pool/:talentId', employerController.updateTalentEntry);
router.get('/offers', employerController.listOffers);
router.post('/offers', employerController.upsertOffer);
router.patch('/offers/:offerId/status', employerController.updateOfferStatus);
router.get('/activity-calendar', employerController.getHiringActivityCalendar);
router.get('/approvals', employerController.listHiringApprovals);
router.post('/approvals', employerController.createHiringApproval);
router.patch('/approvals/:approvalId', employerController.updateHiringApproval);
router.get('/allocations', employerController.listHiringAllocations);
router.post('/allocations', employerController.upsertHiringAllocation);
router.patch('/allocations/:allocationId', employerController.upsertHiringAllocation);
router.delete('/allocations/:allocationId', employerController.removeHiringAllocation);
router.get('/policies', employerController.listHiringPolicies);
router.post('/policies', employerController.upsertHiringPolicy);
router.patch('/policies/:policyId', employerController.upsertHiringPolicy);
router.get('/configurations', employerController.getHiringConfigurations);
router.patch('/configurations', employerController.updateHiringConfigurations);
router.get('/exports', employerController.getExportCenter);
router.get('/interviews/calendar', employerController.getInterviewCalendar);
router.get('/interviews/hub', employerController.getInterviewHub);
router.post('/interviews/send-reminders', employerController.sendInterviewReminders);
router.get('/jobs/:jobId/applications', employerController.listJobApplicants);
router.patch('/applications/bulk', employerController.bulkUpdateApplicants);
router.post('/applications/:applicationId/interview-rounds', employerController.createInterviewRound);
router.patch('/applications/:applicationId/interview-rounds/:roundId', employerController.updateInterviewRound);
router.put('/applications/:applicationId/slots', employerController.saveApplicationSlots);
router.post('/applications/:applicationId/book-slot', employerController.bookApplicationSlot);
router.patch('/applications/:applicationId/status', employerController.updateApplicantStatus);

module.exports = router;
